source 'https://github.com/blodely/LYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.2'

target 'LYPopView_Example' do
  pod 'LYPopView', :path => '../'

  target 'LYPopView_Tests' do
    inherit! :search_paths

    
  end
end
