source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'
project './LYPopView.xcodeproj'


target 'LYPopView_Example' do
	pod 'LYPopView', :path => '../'
	pod 'LYConfigKit'

	target 'LYPopView_Tests' do
		inherit! :search_paths
	end
end
